import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const tataOrbiter = localFont({
  src: "./fonts/TASAOrbiterVF.woff2",
  variable: "--font-tata-orbiter",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${tataOrbiter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
